theme: minima
title: Chang-Wa Huynh
description: Chang-Wa Huynh's homepage
author:
  name: "Chang-Wa Huynh"
  bio: "Assistant Professor in Management"
  location: "Paris, France"
  email: "chuynh@escp.eu"
  employer: "ESCP Business school"
  linkedin: "chang-wa-huynh"
  
